<?php
include("../koneksi.php");
if($_POST){ 
	extract($_POST);
	$intDoc = mysqli_real_escape_string($con,$_POST['intdoc']); 
	$kdBng  = mysqli_real_escape_string($con,$_POST['kdbng']);
	
	$no=1;
	$sqlDB21 = " SELECT 
c.SUPPLIERCODE, 
b.LOTCODE,
b.ITEMTYPECODE,
b.DECOSUBCODE01,
b.DECOSUBCODE02,
b.DECOSUBCODE03,
b.DECOSUBCODE04,
b.DECOSUBCODE05,
b.DECOSUBCODE06,
b.DECOSUBCODE07,
b.DECOSUBCODE08,
b.QUALITYLEVELCODE,
d.MANUFACTURINGDATE,
SUM(b.BASEPRIMARYQUANTITYUNIT) AS KGS,
SUM(b.BASESECONDARYQUANTITYUNIT) AS CONES,
COUNT(b.ELEMENTSCODE) AS QTY,
b.WHSLOCATIONWAREHOUSEZONECODE,
b.WAREHOUSELOCATIONCODE FROM BALANCE b 
LEFT OUTER JOIN LOT c ON c.CODE =b.LOTCODE
LEFT OUTER JOIN (
SELECT ITTSUPPLIERPACKINGLISTBEAN.MANUFACTURINGDATE,ITTSUPPLIERPACKINGLISTBEAN.ITEMELEMENTCODE 
FROM DB2ADMIN.ITTSUPPLIERPACKINGLISTBEAN ITTSUPPLIERPACKINGLISTBEAN ) d
ON b.ELEMENTSCODE =d.ITEMELEMENTCODE
WHERE (b.ITEMTYPECODE ='GYR' OR b.ITEMTYPECODE ='DYR') AND
b.LOGICALWAREHOUSECODE = 'M011' AND 
(
b.WHSLOCATIONWAREHOUSEZONECODE='GB1' OR  
b.WHSLOCATIONWAREHOUSEZONECODE='GB2' OR
b.WHSLOCATIONWAREHOUSEZONECODE='GB5' OR
b.WHSLOCATIONWAREHOUSEZONECODE='GB6' OR 
b.WHSLOCATIONWAREHOUSEZONECODE='GP1' OR 
b.WHSLOCATIONWAREHOUSEZONECODE='GR2' OR 
b.WHSLOCATIONWAREHOUSEZONECODE='GR3' OR 
b.WHSLOCATIONWAREHOUSEZONECODE='LT') AND
CONCAT(trim(b.DECOSUBCODE01),CONCAT(trim(b.DECOSUBCODE02),CONCAT(trim(b.DECOSUBCODE03),CONCAT(trim(b.DECOSUBCODE04),CONCAT(trim(b.DECOSUBCODE05),CONCAT(trim(b.DECOSUBCODE06),CONCAT(trim(b.DECOSUBCODE07),trim(b.DECOSUBCODE08))))))))='$kdBng' 
GROUP BY b.LOTCODE, b.ITEMTYPECODE,
b.DECOSUBCODE01, b.DECOSUBCODE02,
b.DECOSUBCODE03, b.DECOSUBCODE04,
b.DECOSUBCODE05, b.DECOSUBCODE06,
b.DECOSUBCODE07, b.DECOSUBCODE08,
b.QUALITYLEVELCODE,
d.MANUFACTURINGDATE,
b.WHSLOCATIONWAREHOUSEZONECODE,
b.WAREHOUSELOCATIONCODE,c.SUPPLIERCODE ";
	$stmt1   = db2_exec($conn1,$sqlDB21, array('cursor'=>DB2_SCROLLABLE));
	//}				  
    while($rowdb21 = db2_fetch_assoc($stmt1)){
	$lokasi = trim($rowdb21['WHSLOCATIONWAREHOUSEZONECODE'])."-".trim($rowdb21['WAREHOUSELOCATIONCODE']);	
	if($_POST['cek1'][$no]==$no){	
	mysqli_query($con, "INSERT INTO tblambillokasi SET 
	no_doc='$intDoc',		  
	lokasi='$lokasi'");

	}else{
		
	}
	$no++;	
	}
	echo "<script type=\"text/javascript\">
            window.location = \"ListMohonBenang\"
      </script>";
}
?>