<?php
include "../koneksi.php";
ini_set("error_reporting", 1);
$Awal = date("2025-12-05");
//$Awal = date("Y-m-d", strtotime("-2 day"));

if (!function_exists('sqlsrv_query_safe')) {
	function sqlsrv_query_safe($conn, $sql)
	{
		$stmt = sqlsrv_query($conn, $sql);
		if ($stmt === false) {
			error_log('SQLSRV query failed: ' . print_r(sqlsrv_errors(), true) . ' | SQL: ' . $sql);
		}
		return $stmt;
	}
}

$cektgl = sqlsrv_query_safe(
	$con,
	"SELECT 
		CONVERT(char(10), GETDATE(), 120) AS tgl,
		COUNT(tgl_tutup) AS ck,
		DATEPART(hour, GETDATE()) AS jam,
		CONVERT(char(5), GETDATE(), 108) AS jam1
	 FROM dbnow_gdb.tblmasukbenang_11
	 WHERE tgl_tutup='" . $Awal . "'"
);
$dcek = ($cektgl !== false) ? sqlsrv_fetch_array($cektgl, SQLSRV_FETCH_ASSOC) : ['tgl' => $Awal, 'ck' => 0, 'jam' => 0, 'jam1' => '00:00'];
$t1 = strtotime($Awal);
$t2 = strtotime($dcek['tgl']);
$selh = round(abs($t2 - $t1) / (60 * 60 * 45));

if ($dcek['ck'] > 0) {

	echo "<script>";
	echo "alert('Stok Tgl " . $Awal . " Ini Sudah Pernah ditutup')";
	echo "</script>";
} else if ($dcek['jam'] < 6) {
	echo "<script>";
	echo "alert('Tidak Bisa Tutup Sebelum jam 11 Malam Sampai jam 12 Malam, Sekarang Masih Jam " . $dcek['jam1'] . "')";
	echo "</script>";
} else {

	//Masuk Benang Supplier
	$sqlDB21M = " SELECT
					x.TRANSACTIONNUMBER,
					x.DECOSUBCODE01,
					x.DECOSUBCODE02,
					x.DECOSUBCODE03,
					x.DECOSUBCODE04,
					x.DECOSUBCODE05,
					x.DECOSUBCODE06,
					x.DECOSUBCODE07,
					x.DECOSUBCODE08,
					x.DECOSUBCODE09,
					x.DECOSUBCODE10,
					x.ITEMDESCRIPTION,
					x.USERPRIMARYUOMCODE,
					f.SUMMARIZEDDESCRIPTION,
					COUNT(x.ITEMELEMENTCODE) AS QTY_DUS,
					SUM(x.BASEPRIMARYQUANTITY) AS QTY_KG,
					b.LEGALNAME1,
					SUM(x.BASESECONDARYQUANTITY) AS QTY_CONES,
					x.TRANSACTIONDATE,
					m.CHALLANDATE,
					x.TOKENCODE,
					x.ORDERCOUNTERCODE,
					x.ORDERCODE,
					x.ORDERLINE,
					x.LOTCODE,
					m.CHALLANNO,
					CASE
						WHEN NOT bc.WHSLOCATIONWAREHOUSEZONECODE = '' THEN bc.WHSLOCATIONWAREHOUSEZONECODE
						ELSE x.WHSLOCATIONWAREHOUSEZONECODE
					END AS WHSLOCATIONWAREHOUSEZONECODE,
					CASE
						WHEN NOT bc.WAREHOUSELOCATIONCODE = '' THEN bc.WAREHOUSELOCATIONCODE
						ELSE x.WAREHOUSELOCATIONCODE
					END AS WAREHOUSELOCATIONCODE
				FROM
					DB2ADMIN.STOCKTRANSACTION x
				LEFT OUTER JOIN DB2ADMIN.MRNDETAIL m2 ON
					m2.TRANSACTIONNUMBER = x.TRANSACTIONNUMBER
				LEFT OUTER JOIN DB2ADMIN.MRNHEADER m ON
					m.CODE = m2.MRNHEADERCODE
				LEFT OUTER JOIN DB2ADMIN.CUSTOMERSUPPLIERDATA n ON
					x.SUPPLIERCODE = n.CODE
				LEFT OUTER JOIN DB2ADMIN.BUSINESSPARTNER b ON
					b.NUMBERID = n.BUSINESSPARTNERNUMBERID
				LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER f ON
					x.FULLITEMIDENTIFIER = f.IDENTIFIER
				LEFT OUTER JOIN DB2ADMIN.BALANCE bc ON
					bc.ELEMENTSCODE = x.ITEMELEMENTCODE
				WHERE
					m.CHALLANDATE = '$Awal'
					AND (ORDERCOUNTERCODE = 'POYRL'
						OR ORDERCOUNTERCODE = 'POYRI')
					AND x.TOKENCODE = 'RECEIPT'
				GROUP BY
					x.TRANSACTIONNUMBER,
					x.DECOSUBCODE01,
					x.DECOSUBCODE02,
					x.DECOSUBCODE03,
					x.DECOSUBCODE04,
					x.DECOSUBCODE05,
					x.DECOSUBCODE06,
					x.DECOSUBCODE07,
					x.DECOSUBCODE08,
					x.DECOSUBCODE09,
					x.DECOSUBCODE10,
					x.ITEMDESCRIPTION,
					x.USERPRIMARYUOMCODE,
					f.SUMMARIZEDDESCRIPTION,
					x.TRANSACTIONDATE,
					x.TOKENCODE,
					x.ORDERCOUNTERCODE,
					x.LOTCODE,
					m.CHALLANNO,
					m.CHALLANDATE ,
					b.LEGALNAME1,
					x.ORDERLINE,
					x.ORDERCODE,
					bc.WHSLOCATIONWAREHOUSEZONECODE,
					bc.WAREHOUSELOCATIONCODE,
					x.WHSLOCATIONWAREHOUSEZONECODE,
					x.WAREHOUSELOCATIONCODE
				ORDER BY
					x.TRANSACTIONNUMBER ASC";

	$stmt1M   = db2_exec($conn1, $sqlDB21M, array('cursor' => DB2_SCROLLABLE));
	//}				  
	while ($rowdb21M = db2_fetch_assoc($stmt1M)) {

		// $cd=trim($rowdb21['SUBCODE01'])."-".trim($rowdb21['SUBCODE02'])."-".trim($rowdb21['SUBCODE03'])."-".trim($rowdb21['SUBCODE04'])."-".trim($rowdb21['SUBCODE05'])."-".trim($rowdb21['SUBCODE06'])."-".trim($rowdb21['SUBCODE07'])."-".trim($rowdb21['SUBCODE08'])."-".trim($rowdb21['SUBCODE09'])."-".trim($rowdb21['SUBCODE10']);		

		$cd = trim($rowdb21M['DECOSUBCODE01']) . "-" . trim($rowdb21M['DECOSUBCODE02']) . "-"
			. trim($rowdb21M['DECOSUBCODE03']) . "-" . trim($rowdb21M['DECOSUBCODE04']) . "-"
			. trim($rowdb21M['DECOSUBCODE05']) . "-" . trim($rowdb21M['DECOSUBCODE06']) . "-"
			. trim($rowdb21M['DECOSUBCODE07']) . "-" . trim($rowdb21M['DECOSUBCODE08']) . "-"
			. trim($rowdb21M['DECOSUBCODE09']) . "-" . trim($rowdb21M['DECOSUBCODE10']);

		if ($rowdb21M['DESTINATIONWAREHOUSECODE'] == 'M904') {
			$knittM = 'KNITTING ITTI ATAS- BENANG';
		} else if ($rowdb21M['DESTINATIONWAREHOUSECODE'] = 'P501') {
			$knittM = 'KNITTING ITTI- BENANG';
		} else if ($rowdb21M['DESTINATIONWAREHOUSECODE'] = 'M051') {
			$knittM =  'KNITTING A- BENANG';
		} else if ($rowdb21M['DESTINATIONWAREHOUSECODE'] = 'P503') {
			$knittM =  'YARN DYE';
		}

			$poRmpM = sqlsrv_escape_str($rowdb21M['ORDERCODE'] . "-" . $rowdb21M['ORDERLINE']);
			$simpanM = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblmasukbenang_11
										(tgl_masuk, po_rmp, sj_no, tipe, kode, supplier, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
										VALUES (
											'" . $rowdb21M['MRNDATE'] . "',
											LEFT('$poRmpM', COL_LENGTH('dbnow_gdb.tblmasukbenang_11','po_rmp')),
											'" . sqlsrv_escape_str($rowdb21M['CHALLANNO']) . "',
											'GYR',
											'" . sqlsrv_escape_str($cd) . "',
											'" . sqlsrv_escape_str($rowdb21M['LEGALNAME1']) . "',
											'" . sqlsrv_escape_str($rowdb21M['SUMMARIZEDDESCRIPTION']) . "',
											'" . sqlsrv_escape_str($rowdb21M['LOTCODE']) . "',
											'" . sqlsrv_escape_str($rowdb21M['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21M['WAREHOUSELOCATIONCODE']) . "',
											" . (float)$rowdb21M['QTY_DUS'] . ",
											" . (float)$rowdb21M['QTY_CONES'] . ",
											" . round($rowdb21M['QTY_KG'], 2) . ",
											'" . $Awal . "',
											GETDATE()
										)") or die(print_r(sqlsrv_errors(), true));
	}
	//Retur Masuk Benang				
	$sqlDB21RM = " SELECT
					INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
					INTERNALDOCUMENTLINE.ORDERLINE,
					INTERNALDOCUMENTLINE.EXTERNALREFERENCE,
					INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
					INTERNALDOCUMENTLINE.WAREHOUSECODE,
					STOCKTRANSACTION.LOTCODE,
					LOT.SUPPLIERCODE,
					BUSINESSPARTNER.LEGALNAME1,
					STOCKTRANSACTION.TRANSACTIONDATE,
					SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
					COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_ROL,
					SUM(STOCKTRANSACTION.BASESECONDARYQUANTITY) AS QTY_CONES,
					INTERNALDOCUMENTLINE.SUBCODE01,
					INTERNALDOCUMENTLINE.SUBCODE02,
					INTERNALDOCUMENTLINE.SUBCODE03,
					INTERNALDOCUMENTLINE.SUBCODE04,
					INTERNALDOCUMENTLINE.SUBCODE05,
					INTERNALDOCUMENTLINE.SUBCODE06,
					INTERNALDOCUMENTLINE.SUBCODE07,
					INTERNALDOCUMENTLINE.SUBCODE08,
					STOCKTRANSACTION.CREATIONUSER,
					STOCKTRANSACTION.LOGICALWAREHOUSECODE,
					STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
					STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
					FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION
				FROM
					DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION
				LEFT OUTER JOIN DB2ADMIN.INTERNALDOCUMENTLINE INTERNALDOCUMENTLINE ON
					INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE = STOCKTRANSACTION.ORDERCODE
					AND 
				INTERNALDOCUMENTLINE.ORDERLINE = STOCKTRANSACTION.ORDERLINE
					AND INTERNALDOCUMENTLINE.ITEMTYPEAFICODE = STOCKTRANSACTION.ITEMTYPECODE
					AND INTERNALDOCUMENTLINE.INTDOCPROVISIONALCOUNTERCODE = STOCKTRANSACTION.ORDERCOUNTERCODE
					AND INTERNALDOCUMENTLINE.SUBCODE01  = STOCKTRANSACTION.DECOSUBCODE01
					AND INTERNALDOCUMENTLINE.SUBCODE02  = STOCKTRANSACTION.DECOSUBCODE02
					AND INTERNALDOCUMENTLINE.SUBCODE03  = STOCKTRANSACTION.DECOSUBCODE03
					AND INTERNALDOCUMENTLINE.SUBCODE04  = STOCKTRANSACTION.DECOSUBCODE04
					AND INTERNALDOCUMENTLINE.SUBCODE05  = STOCKTRANSACTION.DECOSUBCODE05
					AND INTERNALDOCUMENTLINE.SUBCODE06  = STOCKTRANSACTION.DECOSUBCODE06
					AND INTERNALDOCUMENTLINE.SUBCODE07  = STOCKTRANSACTION.DECOSUBCODE07
					AND INTERNALDOCUMENTLINE.SUBCODE08  = STOCKTRANSACTION.DECOSUBCODE08
				LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
					STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
				LEFT OUTER JOIN LOT ON
					STOCKTRANSACTION.LOTCODE = LOT.CODE
					AND LOT.COMPANYCODE = '100'
					AND 
				STOCKTRANSACTION.ITEMTYPECODE = LOT.ITEMTYPECODE
					AND
				STOCKTRANSACTION.DECOSUBCODE01 = LOT.DECOSUBCODE01
					AND
				STOCKTRANSACTION.DECOSUBCODE02 = LOT.DECOSUBCODE02
					AND
				STOCKTRANSACTION.DECOSUBCODE03 = LOT.DECOSUBCODE03
					AND
				STOCKTRANSACTION.DECOSUBCODE04 = LOT.DECOSUBCODE04
					AND
				STOCKTRANSACTION.DECOSUBCODE05 = LOT.DECOSUBCODE05
					AND
				STOCKTRANSACTION.DECOSUBCODE06 = LOT.DECOSUBCODE06
					AND
				STOCKTRANSACTION.DECOSUBCODE07 = LOT.DECOSUBCODE07
					AND
				STOCKTRANSACTION.DECOSUBCODE08 = LOT.DECOSUBCODE08
				LEFT OUTER JOIN CUSTOMERSUPPLIERDATA ON
					LOT.SUPPLIERCODE = CUSTOMERSUPPLIERDATA.CODE
					AND CUSTOMERSUPPLIERDATA.COMPANYCODE = '100'
					AND CUSTOMERSUPPLIERDATA.TYPE = '2'
				LEFT OUTER JOIN BUSINESSPARTNER ON
					CUSTOMERSUPPLIERDATA.BUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
				WHERE
					(INTERNALDOCUMENTLINE.EXTERNALREFERENCE = 'RETUR'
						OR INTERNALDOCUMENTLINE.EXTERNALREFERENCE = 'RETURAN')
					AND STOCKTRANSACTION.LOGICALWAREHOUSECODE = 'M011'
					AND INTERNALDOCUMENTLINE.ITEMTYPEAFICODE = 'GYR'
					AND STOCKTRANSACTION.TRANSACTIONDATE = '$Awal'
					AND NOT INTERNALDOCUMENTLINE.ORDERLINE IS NULL
				GROUP BY
					STOCKTRANSACTION.LOTCODE,
					INTERNALDOCUMENTLINE.WAREHOUSECODE,
					INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
					INTERNALDOCUMENTLINE.EXTERNALREFERENCE,
					INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
					INTERNALDOCUMENTLINE.ORDERLINE,
					INTERNALDOCUMENTLINE.SUBCODE01,
					INTERNALDOCUMENTLINE.SUBCODE02,
					INTERNALDOCUMENTLINE.SUBCODE03,
					INTERNALDOCUMENTLINE.SUBCODE04,
					INTERNALDOCUMENTLINE.SUBCODE05,
					INTERNALDOCUMENTLINE.SUBCODE06,
					INTERNALDOCUMENTLINE.SUBCODE07,
					INTERNALDOCUMENTLINE.SUBCODE08,
					LOT.SUPPLIERCODE,
					BUSINESSPARTNER.LEGALNAME1,
					STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
					STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
					STOCKTRANSACTION.TRANSACTIONDATE,
					STOCKTRANSACTION.LOGICALWAREHOUSECODE,
					STOCKTRANSACTION.CREATIONUSER,
					FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION ";
	$stmt1RM   = db2_exec($conn1, $sqlDB21RM, array('cursor' => DB2_SCROLLABLE));
	$knittRM = "";
	while ($rowdb21RM = db2_fetch_assoc($stmt1RM)) {
		$bonRM = $rowdb21RM['INTDOCUMENTPROVISIONALCODE'] . "-" . $rowdb21RM['ORDERLINE'];
		if (trim($rowdb21RM['WAREHOUSECODE']) == "M904") {
			$knittRM = 'LT2';
		} else if (trim($rowdb21RM['WAREHOUSECODE']) == "P501") {
			$knittRM = 'LT1';
		} else if (trim($rowdb21RM['WAREHOUSECODE']) == "P503") {
			$knittRM = 'YND';
		}

			$poRmpRM = sqlsrv_escape_str($rowdb21RM['INTDOCUMENTPROVISIONALCODE'] . "-" . $rowdb21RM['ORDERLINE']);
			$simpanRM = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblmasukbenang_11
											(tgl_masuk, po_rmp, no_po, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
											VALUES (
												'" . $rowdb21RM['TRANSACTIONDATE'] . "',
												LEFT('$poRmpRM', COL_LENGTH('dbnow_gdb.tblmasukbenang_11','po_rmp')),
												'" . sqlsrv_escape_str($rowdb21RM['EXTERNALREFERENCE']) . "',
												'" . sqlsrv_escape_str($rowdb21RM['ITEMDESCRIPTION']) . "',
												'GYR',
												'" . sqlsrv_escape_str($rowdb21RM['SUMMARIZEDDESCRIPTION']) . "',
												'" . sqlsrv_escape_str($rowdb21RM['LOTCODE']) . "',
												'" . sqlsrv_escape_str($rowdb21RM['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21RM['WAREHOUSELOCATIONCODE']) . "',
												" . (float)$rowdb21RM['QTY_ROL'] . ",
												" . (float)$rowdb21RM['QTY_CONES'] . ",
												" . round($rowdb21RM['QTY_KG'], 2) . ",
												'" . $Awal . "',
												GETDATE()
											)") or die(print_r(sqlsrv_errors(), true));
	}

	//Retur Masuk Benang DYR				
	$sqlDB21RMY = " SELECT 
				INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
				INTERNALDOCUMENTLINE.ORDERLINE,
				INTERNALDOCUMENTLINE.EXTERNALREFERENCE,
				INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
				INTERNALDOCUMENTLINE.WAREHOUSECODE,
				STOCKTRANSACTION.LOTCODE,  
				LOT.SUPPLIERCODE, 
				BUSINESSPARTNER.LEGALNAME1,
				STOCKTRANSACTION.TRANSACTIONDATE,
				SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
				COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_ROL,
				SUM(STOCKTRANSACTION.BASESECONDARYQUANTITY) AS QTY_CONES,
				INTERNALDOCUMENTLINE.SUBCODE01,
				INTERNALDOCUMENTLINE.SUBCODE02,
				INTERNALDOCUMENTLINE.SUBCODE03,
				INTERNALDOCUMENTLINE.SUBCODE04,
				INTERNALDOCUMENTLINE.SUBCODE05,
				INTERNALDOCUMENTLINE.SUBCODE06,
				INTERNALDOCUMENTLINE.SUBCODE07,
				INTERNALDOCUMENTLINE.SUBCODE08,
				STOCKTRANSACTION.CREATIONUSER,
				STOCKTRANSACTION.LOGICALWAREHOUSECODE,
				STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
				STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
				FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION
				FROM DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION 
				LEFT OUTER JOIN DB2ADMIN.INTERNALDOCUMENTLINE INTERNALDOCUMENTLINE ON INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE=STOCKTRANSACTION.ORDERCODE AND 
				INTERNALDOCUMENTLINE.ORDERLINE=STOCKTRANSACTION.ORDERLINE 
				AND INTERNALDOCUMENTLINE.ITEMTYPEAFICODE = STOCKTRANSACTION.ITEMTYPECODE
				AND INTERNALDOCUMENTLINE.INTDOCPROVISIONALCOUNTERCODE = STOCKTRANSACTION.ORDERCOUNTERCODE
					AND INTERNALDOCUMENTLINE.SUBCODE01  = STOCKTRANSACTION.DECOSUBCODE01
					AND INTERNALDOCUMENTLINE.SUBCODE02  = STOCKTRANSACTION.DECOSUBCODE02
					AND INTERNALDOCUMENTLINE.SUBCODE03  = STOCKTRANSACTION.DECOSUBCODE03
					AND INTERNALDOCUMENTLINE.SUBCODE04  = STOCKTRANSACTION.DECOSUBCODE04
					AND INTERNALDOCUMENTLINE.SUBCODE05  = STOCKTRANSACTION.DECOSUBCODE05
					AND INTERNALDOCUMENTLINE.SUBCODE06  = STOCKTRANSACTION.DECOSUBCODE06
					AND INTERNALDOCUMENTLINE.SUBCODE07  = STOCKTRANSACTION.DECOSUBCODE07
					AND INTERNALDOCUMENTLINE.SUBCODE08  = STOCKTRANSACTION.DECOSUBCODE08
				LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
				STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
				LEFT OUTER JOIN LOT  ON STOCKTRANSACTION.LOTCODE = LOT.CODE AND LOT.COMPANYCODE = '100' AND 
				STOCKTRANSACTION.ITEMTYPECODE = LOT.ITEMTYPECODE AND
				STOCKTRANSACTION.DECOSUBCODE01= LOT.DECOSUBCODE01 AND
				STOCKTRANSACTION.DECOSUBCODE02= LOT.DECOSUBCODE02 AND
				STOCKTRANSACTION.DECOSUBCODE03= LOT.DECOSUBCODE03 AND
				STOCKTRANSACTION.DECOSUBCODE04= LOT.DECOSUBCODE04 AND
				STOCKTRANSACTION.DECOSUBCODE05= LOT.DECOSUBCODE05 AND
				STOCKTRANSACTION.DECOSUBCODE06= LOT.DECOSUBCODE06 AND
				STOCKTRANSACTION.DECOSUBCODE07= LOT.DECOSUBCODE07 AND
				STOCKTRANSACTION.DECOSUBCODE08= LOT.DECOSUBCODE08
				LEFT OUTER JOIN CUSTOMERSUPPLIERDATA  ON LOT.SUPPLIERCODE =CUSTOMERSUPPLIERDATA.CODE AND CUSTOMERSUPPLIERDATA.COMPANYCODE = '100' AND CUSTOMERSUPPLIERDATA.TYPE = '2'
				LEFT OUTER JOIN BUSINESSPARTNER ON CUSTOMERSUPPLIERDATA.BUSINESSPARTNERNUMBERID =BUSINESSPARTNER.NUMBERID
				WHERE (INTERNALDOCUMENTLINE.EXTERNALREFERENCE='RETUR' OR INTERNALDOCUMENTLINE.EXTERNALREFERENCE='RETURAN') AND STOCKTRANSACTION.LOGICALWAREHOUSECODE ='M011' AND INTERNALDOCUMENTLINE.ITEMTYPEAFICODE='DYR' AND
				STOCKTRANSACTION.TRANSACTIONDATE = '$Awal' AND NOT INTERNALDOCUMENTLINE.ORDERLINE IS NULL
				GROUP BY
				STOCKTRANSACTION.LOTCODE,
				INTERNALDOCUMENTLINE.WAREHOUSECODE,
				INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
				INTERNALDOCUMENTLINE.EXTERNALREFERENCE,
				INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
				INTERNALDOCUMENTLINE.ORDERLINE,
				INTERNALDOCUMENTLINE.SUBCODE01,
				INTERNALDOCUMENTLINE.SUBCODE02,
				INTERNALDOCUMENTLINE.SUBCODE03,
				INTERNALDOCUMENTLINE.SUBCODE04,
				INTERNALDOCUMENTLINE.SUBCODE05,
				INTERNALDOCUMENTLINE.SUBCODE06,
				INTERNALDOCUMENTLINE.SUBCODE07,
				INTERNALDOCUMENTLINE.SUBCODE08,
				LOT.SUPPLIERCODE,
				BUSINESSPARTNER.LEGALNAME1,
				STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
				STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
				STOCKTRANSACTION.TRANSACTIONDATE,
				STOCKTRANSACTION.LOGICALWAREHOUSECODE,
				STOCKTRANSACTION.CREATIONUSER,
				FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION ";
	$stmt1RMY   = db2_exec($conn1, $sqlDB21RMY, array('cursor' => DB2_SCROLLABLE));
	$knittRMY = "";
	while ($rowdb21RMY = db2_fetch_assoc($stmt1RMY)) {
		$bonRMY = $rowdb21RMY['INTDOCUMENTPROVISIONALCODE'] . "-" . $rowdb21RMY['ORDERLINE'];
		if (trim($rowdb21RMY['WAREHOUSECODE']) == "M904") {
			$knittRMY = 'LT2';
		} else if (trim($rowdb21RMY['WAREHOUSECODE']) == "P501") {
			$knittRMY = 'LT1';
		} else if (trim($rowdb21RMY['WAREHOUSECODE']) == "P503") {
			$knittRMY = 'YND';
		}

			$simpanRMY = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblmasukbenang_11
											(tgl_masuk, po_rmp, no_po, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
											VALUES (
												'" . $rowdb21RMY['TRANSACTIONDATE'] . "',
												LEFT('" . sqlsrv_escape_str($rowdb21RMY['INTDOCUMENTPROVISIONALCODE'] . "-" . $rowdb21RMY['ORDERLINE']) . "', COL_LENGTH('dbnow_gdb.tblmasukbenang_11','po_rmp')),
												'" . sqlsrv_escape_str($rowdb21RMY['EXTERNALREFERENCE']) . "',
												'" . sqlsrv_escape_str($rowdb21RMY['ITEMDESCRIPTION']) . "',
												'DYR',
												'" . sqlsrv_escape_str($rowdb21RMY['SUMMARIZEDDESCRIPTION']) . "',
												'" . sqlsrv_escape_str($rowdb21RMY['LOTCODE']) . "',
											'" . sqlsrv_escape_str($rowdb21RMY['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21RMY['WAREHOUSELOCATIONCODE']) . "',
											" . (float)$rowdb21RMY['QTY_ROL'] . ",
											" . (float)$rowdb21RMY['QTY_CONES'] . ",
											" . round($rowdb21RMY['QTY_KG'], 2) . ",
											'" . $Awal . "',
											GETDATE()
										)") or die(print_r(sqlsrv_errors(), true));
	}
	// Keluar Benang Prod.
	$sqlDB21K = "SELECT 
				x.INTDOCUMENTPROVISIONALCODE,
				x.ORDERLINE,
				x.EXTERNALREFERENCE,
				x.ITEMDESCRIPTION,
				s.LOTCODE,
				SUM(s.BASEPRIMARYQUANTITY) AS QTY_KG,
				COUNT(s.BASEPRIMARYQUANTITY) AS QTY_ROL,
				SUM(s.BASESECONDARYQUANTITY) AS QTY_CONES,
				x.SUBCODE01,
				x.SUBCODE02,
				x.SUBCODE03,
				x.SUBCODE04,
				x.SUBCODE05,
				x.SUBCODE06,
				x.SUBCODE07,
				x.SUBCODE08,
				x.CONDITIONRETRIEVINGDATE, 
				s.TRANSACTIONDATE,
				s.CREATIONUSER,
				s.LOGICALWAREHOUSECODE,
				s.WHSLOCATIONWAREHOUSEZONECODE,
				s.WAREHOUSELOCATIONCODE,
				a.VALUESTRING AS SUPPLIER,
				f.SUMMARIZEDDESCRIPTION
				FROM DB2ADMIN.INTERNALDOCUMENTLINE x
				LEFT OUTER JOIN STOCKTRANSACTION s ON x.INTDOCUMENTPROVISIONALCODE=s.ORDERCODE AND 
				x.ORDERLINE=s.ORDERLINE 
				LEFT OUTER JOIN FULLITEMKEYDECODER f ON
				s.FULLITEMIDENTIFIER = f.IDENTIFIER
				LEFT OUTER JOIN ADSTORAGE a ON a.UNIQUEID =x.ABSUNIQUEID AND a.NAMENAME ='SuppName'
				WHERE 
				x.CONDITIONRETRIEVINGDATE = '$Awal' AND 
				x.ITEMTYPEAFICODE ='GYR' AND
				s.LOGICALWAREHOUSECODE='M011' AND 
				NOT x.EXTERNALREFERENCE LIKE '%RETUR%' AND 
				NOT x.ORDERLINE IS NULL
				GROUP BY 
				x.INTDOCUMENTPROVISIONALCODE,
				x.ORDERLINE,
				x.EXTERNALREFERENCE,
				x.ITEMDESCRIPTION,
				s.LOTCODE,
				x.SUBCODE01,
				x.SUBCODE02,
				x.SUBCODE03,
				x.SUBCODE04,
				x.SUBCODE05,
				x.SUBCODE06,
				x.SUBCODE07,
				x.SUBCODE08,
				x.CONDITIONRETRIEVINGDATE, 
				s.TRANSACTIONDATE,
				s.CREATIONUSER,
				s.LOGICALWAREHOUSECODE,
				s.WHSLOCATIONWAREHOUSEZONECODE,
				s.WAREHOUSELOCATIONCODE,
				f.SUMMARIZEDDESCRIPTION,
				a.VALUESTRING ";
	$stmt1K   = db2_exec($conn1, $sqlDB21K, array('cursor' => DB2_SCROLLABLE));
	//}				  
	while ($rowdb21K = db2_fetch_assoc($stmt1K)) {
		$bonK = trim($rowdb21K['INTDOCUMENTPROVISIONALCODE']) . "-" . trim($rowdb21K['ORDERLINE']);
		if ($rowdb21K['DESTINATIONWAREHOUSECODE'] == 'M501' or $rowdb21K['DESTINATIONWAREHOUSECODE'] == 'M904') {
			$knittK = 'KNITTING ITTI ATAS- BENANG';
		} else if ($rowdb21K['DESTINATIONWAREHOUSECODE'] = 'P501') {
			$knittK = 'KNITTING ITTI- BENANG';
		} else if ($rowdb21K['DESTINATIONWAREHOUSECODE'] = 'M051') {
			$knittK =  'KNITTING A- BENANG';
		} else if ($rowdb21K['DESTINATIONWAREHOUSECODE'] = 'P503') {
			$knittK =  'YARN DYE';
		}
		$kdbenangK = trim($rowdb21K['SUBCODE01']) . " " . trim($rowdb21K['SUBCODE02']) . " " . trim($rowdb21K['SUBCODE03']) . " " . trim($rowdb21K['SUBCODE04']) . " " . trim($rowdb21K['SUBCODE05']) . " " . trim($rowdb21K['SUBCODE06']) . " " . trim($rowdb21K['SUBCODE07']) . " " . trim($rowdb21K['SUBCODE08']);

		$simpanK = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblkeluarbenang_11
							(tgl_keluar, no_bon, knitt, no_po, itemdesc, supplier, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
							VALUES (
								'" . $rowdb21K['TRANSACTIONDATE'] . "',
								'" . sqlsrv_escape_str($bonK) . "',
								'" . sqlsrv_escape_str($knittK) . "',
								'" . sqlsrv_escape_str($rowdb21K['EXTERNALREFERENCE']) . "',
								'" . sqlsrv_escape_str($rowdb21K['ITEMDESCRIPTION']) . "',
								'" . sqlsrv_escape_str($rowdb21K['SUPPLIER']) . "',
								'" . sqlsrv_escape_str($kdbenangK) . "',
								'GYR',
								'" . sqlsrv_escape_str($rowdb21K['SUMMARIZEDDESCRIPTION']) . "',
								'" . sqlsrv_escape_str($rowdb21K['LOTCODE']) . "',
								'" . sqlsrv_escape_str($rowdb21K['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21K['WAREHOUSELOCATIONCODE']) . "',
								" . (float)$rowdb21K['QTY_ROL'] . ",
								" . (float)$rowdb21K['QTY_CONES'] . ",
								" . round($rowdb21K['QTY_KG'], 2) . ",
								'" . $Awal . "',
								GETDATE()
							)") or die(print_r(sqlsrv_errors(), true));
	}
	// Keluar Benang Prod. DYR
	$sqlDB21KY = "SELECT 
					x.INTDOCUMENTPROVISIONALCODE,
					x.ORDERLINE,
					x.EXTERNALREFERENCE,
					x.ITEMDESCRIPTION,
					s.LOTCODE,
					SUM(s.BASEPRIMARYQUANTITY) AS QTY_KG,
					COUNT(s.BASEPRIMARYQUANTITY) AS QTY_ROL,
					SUM(s.BASESECONDARYQUANTITY) AS QTY_CONES,
					x.SUBCODE01,
					x.SUBCODE02,
					x.SUBCODE03,
					x.SUBCODE04,
					x.SUBCODE05,
					x.SUBCODE06,
					x.SUBCODE07,
					x.SUBCODE08,
					x.CONDITIONRETRIEVINGDATE, 
					s.TRANSACTIONDATE,
					s.CREATIONUSER,
					s.LOGICALWAREHOUSECODE,
					s.WHSLOCATIONWAREHOUSEZONECODE,
					s.WAREHOUSELOCATIONCODE,
					a.VALUESTRING AS SUPPLIER,
					f.SUMMARIZEDDESCRIPTION
					FROM DB2ADMIN.INTERNALDOCUMENTLINE x
					LEFT OUTER JOIN STOCKTRANSACTION s ON x.INTDOCUMENTPROVISIONALCODE=s.ORDERCODE AND 
					x.ORDERLINE=s.ORDERLINE 
					LEFT OUTER JOIN FULLITEMKEYDECODER f ON
					s.FULLITEMIDENTIFIER = f.IDENTIFIER
					LEFT OUTER JOIN ADSTORAGE a ON a.UNIQUEID =x.ABSUNIQUEID AND a.NAMENAME ='SuppName'
					WHERE 
					x.CONDITIONRETRIEVINGDATE = '$Awal' AND 
					x.ITEMTYPEAFICODE ='DYR' AND
					s.LOGICALWAREHOUSECODE='P504' AND 
					NOT x.EXTERNALREFERENCE LIKE '%RETUR%' AND 
					NOT x.ORDERLINE IS NULL
					GROUP BY 
					x.INTDOCUMENTPROVISIONALCODE,
					x.ORDERLINE,
					x.EXTERNALREFERENCE,
					x.ITEMDESCRIPTION,
					s.LOTCODE,
					x.SUBCODE01,
					x.SUBCODE02,
					x.SUBCODE03,
					x.SUBCODE04,
					x.SUBCODE05,
					x.SUBCODE06,
					x.SUBCODE07,
					x.SUBCODE08,
					x.CONDITIONRETRIEVINGDATE, 
					s.TRANSACTIONDATE,
					s.CREATIONUSER,
					s.LOGICALWAREHOUSECODE,
					s.WHSLOCATIONWAREHOUSEZONECODE,
					s.WAREHOUSELOCATIONCODE,
					f.SUMMARIZEDDESCRIPTION,
					a.VALUESTRING ";
	$stmt1KY   = db2_exec($conn1, $sqlDB21KY, array('cursor' => DB2_SCROLLABLE));
	//}				  
	while ($rowdb21KY = db2_fetch_assoc($stmt1KY)) {
		$bonKY = trim($rowdb21KY['INTDOCUMENTPROVISIONALCODE']) . "-" . trim($rowdb21KY['ORDERLINE']);
		if ($rowdb21KY['DESTINATIONWAREHOUSECODE'] == 'M501' or $rowdb21KY['DESTINATIONWAREHOUSECODE'] == 'M904') {
			$knittKY = 'KNITTING ITTI ATAS- BENANG';
		} else if ($rowdb21KY['DESTINATIONWAREHOUSECODE'] = 'P501') {
			$knittKY = 'KNITTING ITTI- BENANG';
		} else if ($rowdb21KY['DESTINATIONWAREHOUSECODE'] = 'M051') {
			$knittKY =  'KNITTING A- BENANG';
		} else if ($rowdb21KY['DESTINATIONWAREHOUSECODE'] = 'P503') {
			$knittKY =  'YARN DYE';
		}
		$kdbenangKY = trim($rowdb21KY['SUBCODE01']) . " " . trim($rowdb21KY['SUBCODE02']) . " " . trim($rowdb21KY['SUBCODE03']) . " " . trim($rowdb21KY['SUBCODE04']) . " " . trim($rowdb21KY['SUBCODE05']) . " " . trim($rowdb21KY['SUBCODE06']) . " " . trim($rowdb21KY['SUBCODE07']) . " " . trim($rowdb21KY['SUBCODE08']);

		$simpanKY = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblkeluarbenang_11
							(tgl_keluar, no_bon, knitt, no_po, itemdesc, supplier, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
							VALUES (
								'" . $rowdb21KY['TRANSACTIONDATE'] . "',
								'" . sqlsrv_escape_str($bonKY) . "',
								'" . sqlsrv_escape_str($knittKY) . "',
								'" . sqlsrv_escape_str($rowdb21KY['EXTERNALREFERENCE']) . "',
								'" . sqlsrv_escape_str($rowdb21KY['ITEMDESCRIPTION']) . "',
								'" . sqlsrv_escape_str($rowdb21KY['SUPPLIER']) . "',
								'" . sqlsrv_escape_str($kdbenangKY) . "',
								'DYR',
								'" . sqlsrv_escape_str($rowdb21KY['SUMMARIZEDDESCRIPTION']) . "',
								'" . sqlsrv_escape_str($rowdb21KY['LOTCODE']) . "',
								'" . sqlsrv_escape_str($rowdb21KY['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21KY['WAREHOUSELOCATIONCODE']) . "',
								" . (float)$rowdb21KY['QTY_ROL'] . ",
								" . (float)$rowdb21KY['QTY_CONES'] . ",
								" . round($rowdb21KY['QTY_KG'], 2) . ",
								'" . $Awal . "',
								GETDATE()
							)") or die(print_r(sqlsrv_errors(), true));
	}
	// Keluar Benang Retur Supplier.
	$sqlDB21RK = "SELECT
					INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
					INTERNALDOCUMENTLINE.ORDERLINE,
					INTERNALDOCUMENT.EXTERNALREFERENCE,
					INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
					STOCKTRANSACTION.LOTCODE,
					SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
					COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_ROL,
					SUM(STOCKTRANSACTION.BASESECONDARYQUANTITY) AS QTY_CONES,
					INTERNALDOCUMENT.EXTERNALREFERENCEDATE,
					INTERNALDOCUMENTLINE.SUBCODE01,
					INTERNALDOCUMENTLINE.SUBCODE02,
					INTERNALDOCUMENTLINE.SUBCODE03,
					INTERNALDOCUMENTLINE.SUBCODE04,
					INTERNALDOCUMENTLINE.SUBCODE05,
					INTERNALDOCUMENTLINE.SUBCODE06,
					INTERNALDOCUMENTLINE.SUBCODE07,
					INTERNALDOCUMENTLINE.SUBCODE08,
					STOCKTRANSACTION.CREATIONUSER,
					STOCKTRANSACTION.LOGICALWAREHOUSECODE,
					STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
					STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
					FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
					ADSTORAGE.VALUESTRING AS SUPP,
					CASE
						WHEN ADSTORAGE2.VALUESTRING = 0 THEN 'DUS'
						WHEN ADSTORAGE2.VALUESTRING = 1 THEN 'KARUNG'
						WHEN ADSTORAGE2.VALUESTRING = 2 THEN 'CONES'
					END AS SATUAN
				FROM
						DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION
				LEFT OUTER JOIN DB2ADMIN.INTERNALDOCUMENTLINE INTERNALDOCUMENTLINE ON
						INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE = STOCKTRANSACTION.ORDERCODE
					AND 
				INTERNALDOCUMENTLINE.ORDERLINE = STOCKTRANSACTION.ORDERLINE
				LEFT OUTER JOIN DB2ADMIN.INTERNALDOCUMENT INTERNALDOCUMENT ON
						INTERNALDOCUMENT.PROVISIONALCOUNTERCODE = INTERNALDOCUMENTLINE.INTDOCPROVISIONALCOUNTERCODE
					AND 
				INTERNALDOCUMENT.PROVISIONALCODE = INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE
				LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
						STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
				LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ADSTORAGE ON
						INTERNALDOCUMENTLINE.ABSUNIQUEID = ADSTORAGE.UNIQUEID
					AND ADSTORAGE.NAMENAME = 'SuppName'
				LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ADSTORAGE2 ON
						INTERNALDOCUMENTLINE.ABSUNIQUEID = ADSTORAGE2.UNIQUEID
					AND ADSTORAGE2.NAMENAME = 'Satuan'
				WHERE
						INTERNALDOCUMENT.EXTERNALREFERENCE LIKE '%RETUR%'
					AND 
				STOCKTRANSACTION.LOGICALWAREHOUSECODE = 'M011'
					AND
				INTERNALDOCUMENT.EXTERNALREFERENCEDATE = '$Awal'
					AND NOT INTERNALDOCUMENTLINE.ORDERLINE IS NULL
				GROUP BY
						STOCKTRANSACTION.LOTCODE,
						INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
						INTERNALDOCUMENT.EXTERNALREFERENCE,
						INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
						INTERNALDOCUMENT.EXTERNALREFERENCEDATE,
						INTERNALDOCUMENTLINE.ORDERLINE,
						INTERNALDOCUMENTLINE.SUBCODE01,
						INTERNALDOCUMENTLINE.SUBCODE02,
						INTERNALDOCUMENTLINE.SUBCODE03,
						INTERNALDOCUMENTLINE.SUBCODE04,
						INTERNALDOCUMENTLINE.SUBCODE05,
						INTERNALDOCUMENTLINE.SUBCODE06,
						INTERNALDOCUMENTLINE.SUBCODE07,
						INTERNALDOCUMENTLINE.SUBCODE08,
						STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
						STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
						STOCKTRANSACTION.LOGICALWAREHOUSECODE,
						STOCKTRANSACTION.CREATIONUSER,
						FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
						ADSTORAGE.VALUESTRING,
						ADSTORAGE2.VALUESTRING ";
	$stmt1RK   = db2_exec($conn1, $sqlDB21RK, array('cursor' => DB2_SCROLLABLE));
	//}				  
	while ($rowdb21RK = db2_fetch_assoc($stmt1RK)) {
		$bonRK = trim($rowdb21RK['INTDOCUMENTPROVISIONALCODE']) . "-" . trim($rowdb21RK['ORDERLINE']);
		if ($rowdb21RK['DESTINATIONWAREHOUSECODE'] == 'M501' or $rowdb21RK['DESTINATIONWAREHOUSECODE'] == 'M904') {
			$knittRK = 'KNITTING ITTI ATAS- BENANG';
		} else if ($rowdb21RK['DESTINATIONWAREHOUSECODE'] = 'P501') {
			$knittRK = 'KNITTING ITTI- BENANG';
		} else if ($rowdb21RK['DESTINATIONWAREHOUSECODE'] = 'M051') {
			$knittRK =  'KNITTING A- BENANG';
		} else if ($rowdb21RK['DESTINATIONWAREHOUSECODE'] = 'P503') {
			$knittRK =  'YARN DYE';
		}
		$kdbenangRK = trim($rowdb21RK['SUBCODE01']) . " " . trim($rowdb21RK['SUBCODE02']) . " " . trim($rowdb21RK['SUBCODE03']) . " " . trim($rowdb21RK['SUBCODE04']) . " " . trim($rowdb21RK['SUBCODE05']) . " " . trim($rowdb21RK['SUBCODE06']) . " " . trim($rowdb21RK['SUBCODE07']) . " " . trim($rowdb21RK['SUBCODE08']);

		$simpanRK = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblkeluarbenang_11
												(tgl_keluar, no_bon, knitt, no_po, itemdesc, supplier, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
												VALUES (
													'" . $rowdb21RK['TRANSACTIONDATE'] . "',
													'" . sqlsrv_escape_str($bonRK) . "',
													'" . sqlsrv_escape_str($knittRK) . "',
													'" . sqlsrv_escape_str($rowdb21RK['EXTERNALREFERENCE']) . "',
													'" . sqlsrv_escape_str($rowdb21RK['ITEMDESCRIPTION']) . "',
													'" . sqlsrv_escape_str($rowdb21RK['SUPP']) . "',
													'" . sqlsrv_escape_str($kdbenangRK) . "',
													'GYR',
													'" . sqlsrv_escape_str($rowdb21RK['SUMMARIZEDDESCRIPTION']) . "',
													'" . sqlsrv_escape_str($rowdb21RK['LOTCODE']) . "',
													'" . sqlsrv_escape_str($rowdb21RK['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21RK['WAREHOUSELOCATIONCODE']) . "',
													" . (float)$rowdb21RK['QTY_ROL'] . ",
													" . (float)$rowdb21RK['QTY_CONES'] . ",
													" . round($rowdb21RK['QTY_KG'], 2) . ",
													'" . $Awal . "',
													GETDATE()
												)") or die(print_r(sqlsrv_errors(), true));
	}

	// Jual Benang.
	$sqlDB21KJ = "SELECT 
					INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
					INTERNALDOCUMENTLINE.ORDERLINE,
					INTERNALDOCUMENT.EXTERNALREFERENCE,
					INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
					STOCKTRANSACTION.LOTCODE,
					SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
					COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_ROL,
					SUM(STOCKTRANSACTION.BASESECONDARYQUANTITY) AS QTY_CONES,
					INTERNALDOCUMENT.EXTERNALREFERENCEDATE,
					INTERNALDOCUMENTLINE.SUBCODE01,
					INTERNALDOCUMENTLINE.SUBCODE02,
					INTERNALDOCUMENTLINE.SUBCODE03,
					INTERNALDOCUMENTLINE.SUBCODE04,
					INTERNALDOCUMENTLINE.SUBCODE05,
					INTERNALDOCUMENTLINE.SUBCODE06,
					INTERNALDOCUMENTLINE.SUBCODE07,
					INTERNALDOCUMENTLINE.SUBCODE08,
					STOCKTRANSACTION.CREATIONUSER,
					STOCKTRANSACTION.LOGICALWAREHOUSECODE,
					STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
					STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
					FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
					ADSTORAGE.VALUESTRING AS SUPP,
						CASE
							WHEN ADSTORAGE2.VALUESTRING = 0 THEN 'DUS'
							WHEN ADSTORAGE2.VALUESTRING = 1 THEN 'KARUNG'
							WHEN ADSTORAGE2.VALUESTRING = 2 THEN 'CONES'
						END AS SATUAN
					FROM DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION 
					LEFT OUTER JOIN DB2ADMIN.INTERNALDOCUMENTLINE INTERNALDOCUMENTLINE ON INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE=STOCKTRANSACTION.ORDERCODE AND 
					INTERNALDOCUMENTLINE.ORDERLINE=STOCKTRANSACTION.ORDERLINE
					LEFT OUTER JOIN DB2ADMIN.INTERNALDOCUMENT INTERNALDOCUMENT ON INTERNALDOCUMENT.PROVISIONALCOUNTERCODE = INTERNALDOCUMENTLINE.INTDOCPROVISIONALCOUNTERCODE AND 
					INTERNALDOCUMENT.PROVISIONALCODE = INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE  
					LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
					STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
					LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ADSTORAGE ON
							INTERNALDOCUMENTLINE.ABSUNIQUEID = ADSTORAGE.UNIQUEID
						AND ADSTORAGE.NAMENAME = 'SuppName'
					LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ADSTORAGE2 ON
							INTERNALDOCUMENTLINE.ABSUNIQUEID = ADSTORAGE2.UNIQUEID
						AND ADSTORAGE2.NAMENAME = 'Satuan'
					WHERE INTERNALDOCUMENT.EXTERNALREFERENCE LIKE '%JUAL%' AND 
					STOCKTRANSACTION.LOGICALWAREHOUSECODE ='M011' AND
					INTERNALDOCUMENT.EXTERNALREFERENCEDATE = '$Awal' AND NOT INTERNALDOCUMENTLINE.ORDERLINE IS NULL
					GROUP BY
					STOCKTRANSACTION.LOTCODE,
					INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE,
					INTERNALDOCUMENT.EXTERNALREFERENCE,
					INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
					INTERNALDOCUMENT.EXTERNALREFERENCEDATE,
					INTERNALDOCUMENTLINE.ORDERLINE,
					INTERNALDOCUMENTLINE.SUBCODE01,
					INTERNALDOCUMENTLINE.SUBCODE02,
					INTERNALDOCUMENTLINE.SUBCODE03,
					INTERNALDOCUMENTLINE.SUBCODE04,
					INTERNALDOCUMENTLINE.SUBCODE05,
					INTERNALDOCUMENTLINE.SUBCODE06,
					INTERNALDOCUMENTLINE.SUBCODE07,
					INTERNALDOCUMENTLINE.SUBCODE08,
					STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
					STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
					STOCKTRANSACTION.LOGICALWAREHOUSECODE,
					STOCKTRANSACTION.CREATIONUSER,
					FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
					ADSTORAGE.VALUESTRING,
					ADSTORAGE2.VALUESTRING ";
	$stmt1KJ   = db2_exec($conn1, $sqlDB21KJ, array('cursor' => DB2_SCROLLABLE));
	//}				  
	while ($rowdb21KJ = db2_fetch_assoc($stmt1KJ)) {
		$bonKJ = trim($rowdb21KJ['INTDOCUMENTPROVISIONALCODE']) . "-" . trim($rowdb21KJ['ORDERLINE']);
		if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] == 'M501' or $rowdb21KJ['DESTINATIONWAREHOUSECODE'] == 'M904') {
			$knittKJ = 'KNITTING ITTI ATAS- BENANG';
		} else if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] = 'P501') {
			$knittKJ = 'KNITTING ITTI- BENANG';
		} else if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] = 'M051') {
			$knittKJ =  'KNITTING A- BENANG';
		} else if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] = 'P503') {
			$knittKJ =  'YARN DYE';
		}
		$kdbenangKJ = trim($rowdb21KJ['SUBCODE01']) . " " . trim($rowdb21KJ['SUBCODE02']) . " " . trim($rowdb21KJ['SUBCODE03']) . " " . trim($rowdb21KJ['SUBCODE04']) . " " . trim($rowdb21KJ['SUBCODE05']) . " " . trim($rowdb21KJ['SUBCODE06']) . " " . trim($rowdb21KJ['SUBCODE07']) . " " . trim($rowdb21KJ['SUBCODE08']);

		$simpanKJ = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblkeluarbenang_11
												(tgl_keluar, no_bon, knitt, no_po, itemdesc, supplier, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
												VALUES (
													'" . $rowdb21KJ['TRANSACTIONDATE'] . "',
													'" . sqlsrv_escape_str($bonRK) . "',
													'" . sqlsrv_escape_str($knittKJ) . "',
													'" . sqlsrv_escape_str($rowdb21KJ['EXTERNALREFERENCE']) . "',
													'" . sqlsrv_escape_str($rowdb21KJ['ITEMDESCRIPTION']) . "',
													'" . sqlsrv_escape_str($rowdb21KJ['SUPP']) . "',
													'" . sqlsrv_escape_str($rowdb21KJ['DECOSUBCODE01'] . " " . $rowdb21KJ['DECOSUBCODE02'] . " " . $rowdb21KJ['DECOSUBCODE03'] . " " . $rowdb21KJ['DECOSUBCODE04'] . " " . $rowdb21KJ['DECOSUBCODE05'] . " " . $rowdb21KJ['DECOSUBCODE06'] . " " . $rowdb21KJ['DECOSUBCODE07'] . " " . $rowdb21KJ['DECOSUBCODE08']) . "',
													'GYR',
													'" . sqlsrv_escape_str($rowdb21KJ['SUMMARIZEDDESCRIPTION']) . "',
													'" . sqlsrv_escape_str($rowdb21KJ['LOTCODE']) . "',
													'" . sqlsrv_escape_str($rowdb21KJ['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21KJ['WAREHOUSELOCATIONCODE']) . "',
													" . (float)$rowdb21KJ['QTY_ROL'] . ",
													" . (float)$rowdb21KJ['QTY_CONES'] . ",
													" . round($rowdb21KJ['QTY_KG'], 2) . ",
													'" . $Awal . "',
													GETDATE()
												)") or die(print_r(sqlsrv_errors(), true));
	}

	// Jual Benang RMP.
	$sqlDB21KJ = "SELECT
				s.TRANSACTIONDATE,
				SUM(s.BASEPRIMARYQUANTITY) AS QTY_KG,
				COUNT(s.BASEPRIMARYQUANTITY) AS QTY_ROL,
				SUM(s.BASESECONDARYQUANTITY) AS QTY_CONES,
				s.LOTCODE,
				s.ORDERCODE,
				s.ORDERLINE,
				s.DECOSUBCODE01,
				s.DECOSUBCODE02,
				s.DECOSUBCODE03,
				s.DECOSUBCODE04,
				s.DECOSUBCODE05,
				s.DECOSUBCODE06,
				s.DECOSUBCODE07,
				s.DECOSUBCODE08,
				s.WHSLOCATIONWAREHOUSEZONECODE,
				s.WAREHOUSELOCATIONCODE,
				s.CREATIONUSER, 
				sl.ITEMDESCRIPTION,
				sl.EXTERNALREFERENCE,
				l.SUPPLIERCODE,
				b.LEGALNAME1,
				f.SUMMARIZEDDESCRIPTION
				FROM
				STOCKTRANSACTION s
				LEFT OUTER JOIN SALESDOCUMENTLINE sl ON
				sl.SALESDOCUMENTPROVISIONALCODE = s.ORDERCODE
				AND sl.ORDERLINE = s.ORDERLINE
				LEFT OUTER JOIN LOT l ON
				l.CODE = s.LOTCODE
				LEFT OUTER JOIN CUSTOMERSUPPLIERDATA c ON
				c.CODE = l.SUPPLIERCODE
				LEFT OUTER JOIN BUSINESSPARTNER b ON
				b.NUMBERID = c.BUSINESSPARTNERNUMBERID
				LEFT OUTER JOIN FULLITEMKEYDECODER f ON
				s.FULLITEMIDENTIFIER = f.IDENTIFIER
				WHERE
				s.ORDERCOUNTERCODE = 'PCAPROV'
				AND s.ITEMTYPECODE = 'GYR'
				AND s.LOGICALWAREHOUSECODE = 'M011'
				AND s.TRANSACTIONDATE = '$Awal'
				GROUP BY
				s.TRANSACTIONDATE,
				s.LOTCODE,
				s.ORDERCODE,
				s.ORDERLINE,
				s.DECOSUBCODE01,
				s.DECOSUBCODE02,
				s.DECOSUBCODE03,
				s.DECOSUBCODE04,
				s.DECOSUBCODE05,
				s.DECOSUBCODE06,
				s.DECOSUBCODE07,
				s.DECOSUBCODE08,
				s.WHSLOCATIONWAREHOUSEZONECODE,
				s.WAREHOUSELOCATIONCODE,
				s.CREATIONUSER, 
				sl.ITEMDESCRIPTION,
				sl.EXTERNALREFERENCE,
				l.SUPPLIERCODE,
				b.LEGALNAME1,
				f.SUMMARIZEDDESCRIPTION ";
	$stmt1KJ   = db2_exec($conn1, $sqlDB21KJ, array('cursor' => DB2_SCROLLABLE));
	//}				  
	while ($rowdb21KJ = db2_fetch_assoc($stmt1KJ)) {
		$bonKJ = trim($rowdb21KJ['ORDERCODE']) . "-" . trim($rowdb21KJ['ORDERLINE']);
		if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] == 'M501' or $rowdb21KJ['DESTINATIONWAREHOUSECODE'] == 'M904') {
			$knittKJ = 'KNITTING ITTI ATAS- BENANG';
		} else if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] = 'P501') {
			$knittKJ = 'KNITTING ITTI- BENANG';
		} else if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] = 'M051') {
			$knittKJ =  'KNITTING A- BENANG';
		} else if ($rowdb21KJ['DESTINATIONWAREHOUSECODE'] = 'P503') {
			$knittKJ =  'YARN DYE';
		}
		$kdbenangKJ = trim($rowdb21KJ['DECOSUBCODE01']) . " " . trim($rowdb21KJ['DECOSUBCODE02']) . " " . trim($rowdb21KJ['DECOSUBCODE03']) . " " . trim($rowdb21KJ['DECOSUBCODE04']) . " " . trim($rowdb21KJ['DECOSUBCODE05']) . " " . trim($rowdb21KJ['DECOSUBCODE06']) . " " . trim($rowdb21KJ['DECOSUBCODE07']) . " " . trim($rowdb21KJ['DECOSUBCODE08']);

			$simpanKJ = sqlsrv_query_safe($con, "INSERT INTO dbnow_gdb.tblkeluarbenang_11
											(tgl_keluar, no_bon, knitt, no_po, itemdesc, supplier, kode, tipe, jenis_benang, lot, blok, qty, cones, berat, tgl_tutup, tgl_buat)
											VALUES (
												'" . $rowdb21KJ['TRANSACTIONDATE'] . "',
												'" . sqlsrv_escape_str($bonRK) . "',
												'" . sqlsrv_escape_str($knittKJ) . "',
												'" . sqlsrv_escape_str($rowdb21KJ['EXTERNALREFERENCE']) . "',
												'" . sqlsrv_escape_str($rowdb21KJ['ITEMDESCRIPTION']) . "',
												'" . sqlsrv_escape_str($rowdb21KJ['LEGALNAME1']) . "',
												'" . sqlsrv_escape_str($rowdb21KJ['DECOSUBCODE01'] . " " . $rowdb21KJ['DECOSUBCODE02'] . " " . $rowdb21KJ['DECOSUBCODE03'] . " " . $rowdb21KJ['DECOSUBCODE04'] . " " . $rowdb21KJ['DECOSUBCODE05'] . " " . $rowdb21KJ['DECOSUBCODE06'] . " " . $rowdb21KJ['DECOSUBCODE07'] . " " . $rowdb21KJ['DECOSUBCODE08']) . "',
												'GYR',
												'" . sqlsrv_escape_str($rowdb21KJ['SUMMARIZEDDESCRIPTION']) . "',
												'" . sqlsrv_escape_str($rowdb21KJ['LOTCODE']) . "',
												'" . sqlsrv_escape_str($rowdb21KJ['WHSLOCATIONWAREHOUSEZONECODE'] . "-" . $rowdb21KJ['WAREHOUSELOCATIONCODE']) . "',
												" . (float)$rowdb21KJ['QTY_ROL'] . ",
												" . (float)$rowdb21KJ['QTY_CONES'] . ",
												" . round($rowdb21KJ['QTY_KG'], 2) . ",
												'" . $Awal . "',
												GETDATE()
											)") or die(print_r(sqlsrv_errors(), true));
	}
	if($simpanM){
		echo "<script>";
		echo "alert('Stok Tgl " . $Awal . " Sudah ditutup')";
		echo "</script>";
		echo "<meta http-equiv='refresh' content='0; url=TutupInOutHarianAuto.php?note=Berhasil'>";
	}else{
		echo "<script>";
		echo "alert('Gagal Menyimpan Masuk Benang Prod.')";
		echo "</script>";
		echo "<meta http-equiv='refresh' content='0; url=TutupInOutHarianAuto.php?note=Gagal'>";
	}
}
